export const defaultPageStyle = {
    width: "360mm",
    backgroundColor: "white",
    color: "",
    height: "200mm",
    padding: "0px",
    borderWidth: "0px",
    borderColor: "#000000",
    borderStyle: "solid",
    backgroundImage: "",
    backgroundSize: "auto",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundAttachment: "scroll",
    backgroundOrigin: "border-box",
    backgroundClip: "content-box",
}

export const rectDefaultStyle = {
    borderWidth: "1px",
    borderColor: "#1d1d1d",
    borderStyle: "solid",
    borderLeftWidth: "1px",
    borderLeftColor: "#1d1d1d",
    borderLeftStyle: "solid",
    borderRightWidth: "1px",
    borderRightColor: "#1d1d1d",
    borderRightStyle: "solid",
    borderTopWidth: "1px",
    borderTopColor: "#1d1d1d",
    borderTopStyle: "solid",
    borderBottomWidth: "1px",
    borderBottomColor: "#1d1d1d",
    borderBottomStyle: "solid",
    width: "200px",
    borderRadius: "0px",
    borderTopLeftRadius: "0px",
    borderTopRightRadius: "0px",
    borderBottomLeftRadius: "0px",
    borderBottomRightRadius: "0px",
    left: "0",
    top: "0",
    height: "80px",
    opacity: "1",
    backgroundColor: "transparent",
    zIndex: "1",
    backgroundImage: "",
    backgroundSize: "auto",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundAttachment: "scroll",
    backgroundOrigin: "border-box",
    backgroundClip: "content-box",
    transform: "rotate(0deg)",
    rotateRight: "0",
    rotateLeft: "0"

}

export const lineDefaultStyle = {
    width: "200px",
    borderRadius: "0px",
    left: "0",
    top: "0",
    height: "1px",
    opacity: "10",
    backgroundColor: "#000000",
    zIndex: "1",
    transform: "rotate(0deg)",
    rotateRight: "0",
    rotateLeft: "0"
}


export const imageDefaultStyle = {
    borderWidth: "1px",
    borderColor: "#1d1d1d",
    borderStyle: "solid",
    borderLeftWidth: "1px",
    borderLeftColor: "#1d1d1d",
    borderLeftStyle: "solid",
    borderRightWidth: "1px",
    borderRightColor: "#1d1d1d",
    borderRightStyle: "solid",
    borderTopWidth: "1px",
    borderTopColor: "#1d1d1d",
    borderTopStyle: "solid",
    borderBottomWidth: "1px",
    borderBottomColor: "#1d1d1d",
    borderBottomStyle: "solid",
    width: "200px",
    borderTopLeftRadius: "0px",
    borderTopRightRadius: "0px",
    borderBottomLeftRadius: "0px",
    borderBottomRightRadius: "0px",
    borderRadius: "0px",
    left: "0",
    top: "0",
    height: "80px",
    opacity: "1",
    zIndex: "1",
    transform: "rotate(0deg)",
    rotateRight: "0",
    rotateLeft: "0"
}


export const tableDefaultStyle = {
    borderWidth: "1px",
    borderColor: "#1d1d1d",
    borderStyle: "solid",
    borderLeftWidth: "1px",
    borderLeftColor: "#1d1d1d",
    borderLeftStyle: "solid",
    borderRightWidth: "1px",
    borderRightColor: "#1d1d1d",
    borderRightStyle: "solid",
    borderTopWidth: "1px",
    borderTopColor: "#1d1d1d",
    borderTopStyle: "solid",
    borderBottomWidth: "1px",
    borderBottomColor: "#1d1d1d",
    borderBottomStyle: "solid",
    tableLayout: "auto",
    minWidth: "min-content",  
    left: "0",
    top: "0",
    height: "auto",
    opacity: "1",
    backgroundColor: "transparent",
    zIndex: "1",
    fontFamily: "sans-serif",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: "400",
    textDecoration: "",
    textAlign: "",
    backgroundImage: "",
    backgroundSize: "auto",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundAttachment: "fixed",
    backgroundOrigin: "border-box",
    borderCollapse: "collapse",
    backgroundClip: "content-box",
    letterSpacing: "normal",
    borderRadius: "0px",
    borderTopLeftRadius: "0px",
    borderTopRightRadius: "0px",
    borderBottomLeftRadius: "0px",
    borderBottomRightRadius: "0px",
    transform: "rotate(0deg)",
    rotateRight: "0",
    rotateLeft: "0"
}


export const textboxDefaultStyle = {
    borderWidth: "1px",
    borderColor: "#1d1d1d",
    borderStyle: "solid",
    borderLeftWidth: "1px",
    borderLeftColor: "#1d1d1d",
    borderLeftStyle: "solid",
    borderRightWidth: "1px",
    borderRightColor: "#1d1d1d",
    borderRightStyle: "solid",
    borderTopWidth: "1px",
    borderTopColor: "#1d1d1d",
    borderTopStyle: "solid",
    borderBottomWidth: "1px",
    borderBottomColor: "#1d1d1d",
    borderBottomStyle: "solid",
    color: "#000000",
    width: "220px",
    left: "0",
    top: "0",
    height: "80px",
    opacity: "1",
    backgroundColor: "transparent",
    zIndex: "1",
    fontFamily: "sans-serif",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: "400",
    textDecoration: "none",
    textAlign: "left",
    lineHeight: "normal",
    letterSpacing: "0px",
    rotate: "0deg",
    borderRadius: "0px",
    borderTopLeftRadius: "0px",
    borderTopRightRadius: "0px",
    borderBottomLeftRadius: "0px",
    borderBottomRightRadius: "0px",
    backgroundImage: "",
    backgroundSize: "auto",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundAttachment: "fixed",
    backgroundOrigin: "border-box",
    backgroundClip: "content-box",
    verticalAlign: "baseline",
    paddingLeft : "0px",
    paddingRight : "0px",
    paddingTop : "0px",
    paddingBottom : "0px",
    transform: "rotate(0deg)",
    rotateRight: "0",
    rotateLeft: "0"
}

export const circleDefaultStyle = {
    borderWidth: "1px",
    borderColor: "#000000",
    borderStyle: "solid",
    color: "#000000",
    size: "200px",
    left: "0px",
    top: "0px",
    opacity: "1",
    backgroundColor: "transparent",
    zIndex: "1",
    backgroundImage: "",
    backgroundSize: "auto",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundAttachment: "scroll",
    backgroundOrigin: "border-box",
    backgroundClip: "content-box",
    transform: "rotate(0deg)",
    rotateRight: "0",
    rotateLeft: "0"
}

export const squareDefaultStyle = {
    borderWidth: "1px",
    borderColor: "#1d1d1d",
    borderStyle: "solid",
    borderLeftWidth: "1px",
    borderLeftColor: "#1d1d1d",
    borderLeftStyle: "solid",
    borderRightWidth: "1px",
    borderRightColor: "#1d1d1d",
    borderRightStyle: "solid",
    borderTopWidth: "1px",
    borderTopColor: "#1d1d1d",
    borderTopStyle: "solid",
    borderBottomWidth: "1px",
    borderBottomColor: "#1d1d1d",
    borderBottomStyle: "solid",
    color: "#000000",
    size: "150px",
    left: "100px",
    top: "0",
    opacity: "1",
    backgroundColor: "transparent",
    zIndex: "1",
    backgroundImage: "",
    backgroundSize: "auto",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundAttachment: "scroll",
    backgroundOrigin: "border-box",
    backgroundClip: "content-box",
    borderRadius: "0px",
    borderTopLeftRadius: "0px",
    borderTopRightRadius: "0px",
    borderBottomLeftRadius: "0px",
    borderBottomRightRadius: "0px",
    transform: "rotate(0deg)",
    rotateRight: "0",
    rotateLeft: "0"     
}


export const tableCellDefaultStyle = {
    borderWidth: "1px",
    borderColor: "#1d1d1d",
    borderStyle: "solid",
    color: "#000000",
    width : "fit-content",
    // minWidth: "140px",
    padding: "0",
    borderRadius: "0px",
    height: "35",
    opacity: "1",
    backgroundColor: "transparent",
    zIndex: "1",
    fontFamily: "sans-serif",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: "400",
    textDecoration: "",
    textAlign: "",
    backgroundImage: "",
    backgroundSize: "auto",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundAttachment: "fixed",
    backgroundOrigin: "border-box",
    backgroundClip: "content-box",
    borderCollapse: "collapse",
    letterSpacing: "inherit",
    verticalAlign: "baseline",
}


export const tableRowDefaultStyle = {
    borderWidth: "inherit",
    borderColor: "#1d1d1d",
    borderStyle: "inherit",
    color: "#inherit",
    width: "inherit",
    padding: "inherit",
    borderRadius: "inherit",
    height: "inherit",
    opacity: "inherit",
    backgroundColor: "inherit",
    zIndex: "inherit",
    fontFamily: "inherit",
    fontSize: "inherit",
    fontStyle: "normal",
    fontWeight: "inherit",
    textDecoration: "inherit",
    textAlign: "inherit",
    backgroundImage: "",
    backgroundSize: "inherit",
    backgroundRepeat: "inherit",
    backgroundPosition: "inherit",
    backgroundAttachment: "inherit",
    backgroundOrigin: "inherit",
    backgroundClip: "inherit",
    borderCollapse: "inherit",
    letterSpacing: "inherit",
}

export const tableHeadCellDefaultStyle = {
    borderWidth: "1px",
    borderColor: "inherit",
    borderStyle: "solid",
    color: "#000000",
    width: "140px",
    padding: "0px",
    borderRadius: "0px",
    height: "35",
    opacity: "1",
    backgroundColor: "transparent",
    zIndex: "1",
    fontFamily: "sans-serif",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: "400",
    textDecoration: "",
    textAlign: "",
    backgroundImage: "",
    backgroundSize: "auto",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundAttachment: "fixed",
    backgroundOrigin: "border-box",
    backgroundClip: "content-box",
    borderCollapse: "collapse",
    letterSpacing: "inherit",
    verticalAlign: "baseline"
}
