name: Deploy to IIS Sandbox

on:
  workflow_dispatch:
          
jobs:
  deploy:
    runs-on: [self-hosted, zibma-s2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build React project
        run: npm run build --omit=dev

      - name: Publish to IIS
        run: |

          $sourcePath = "${{ github.workspace }}\build\*"
          $destinationPath = "C:\Zibma\SchoolSite\OnlineSite\Zibma.MS.Sandbox\Frontend\Backup"

          Remove-Item $destinationPath\* -Recurse -Force
          Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force
