

// import '@fortawesome/fontawesome-svg-core/styles.css'
// import { config } from '@fortawesome/fontawesome-svg-core'


// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
// import { faHouse, faAddressCard, faHashtag, faList, faSitemap, faShieldHalved, faChevronDown, faEnvelopesBulk } from '@fortawesome/free-solid-svg-icons';

// import { LocalizationProvider } from '@mui/x-date-pickers';
// import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'

// import { Link } from 'react-router-dom';
// import { useLocation } from 'react-router-dom';
// import { useEffect, useState } from 'react';
// // import PageLoader from '../Components/PageLoader';

// import { decode } from "../Utils/Config/axiosConfig";
// import NavbarLink from '../UIComponents/Navbar/NavbarLink';
// import { BiSolidUser } from 'react-icons/bi';
// import { AiFillHome } from 'react-icons/ai';
// import { BsFillCloudCheckFill } from 'react-icons/bs';
// import { GoProjectRoadmap } from 'react-icons/go';

// config.autoAddCss = false

// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

// export default function NewNavbar({ showSidebar,

// }) {
//     // const [showLoader, setShowLoader] = useState(false);

//     const __location = useLocation()

//     const pathName = __location.pathname;

//     const [openPrjectAccordian, setOpenProjectAccordian] = useState(getInitialForAccordian("project"))
//     const [openPostAccordian, setOpenPostAccordian] = useState(getInitialForAccordian("post"))

//     // const navigate = useNavigate();

//     // const goTo = (route) => {
//     //   // setIsLoading(true)
//     //   //navigate(route);

//     // };
//     useEffect(
//         () => {
//             if (openPrjectAccordian) setOpenPostAccordian(false)
//         }, [openPrjectAccordian]
//     )

//     useEffect(
//         () => {
//             if (openPostAccordian) setOpenProjectAccordian(false)
//         }, [openPostAccordian]
//     )

//     function getInitialForAccordian(accordian) {
//         if (accordian === "project") {
//             return ((pathName === '/project' || pathName.includes("/project/")) || (pathName === '/project-group' || pathName.includes("/project-group")))
//         }
//         if (accordian === "post") {
//             return ((pathName === '/post-category' || pathName.includes("/post-category/")) || (pathName === '/post' || pathName.includes("/post")))
//         }
//     }

//     return (



//         <LocalizationProvider dateAdapter={AdapterDayjs}>
//             <div className={`flex flex-col`}>
//                 {/* <PageLoader show={showLoader} /> */}

//                 <div className='body flex h-[calc(100%-0px)] max-[991px]:relative'>

//                     <div className={`sidebar ${showSidebar ? 'w-[220px]' : 'w-0'} h-full transition-[all] duration-[250ms] bg-white font-mulish text-[13px] font-bold overflow-y-auto`}>

//                         <NavbarLink title={"Dashboard"} link={"/dashboard"} icon={
//                             <AiFillHome size={18} />
//                         } />


//                         {
//                             decode?.claims.includes(26) ? <NavbarLink title={"User"} link={"/user"} icon={
//                                 <BiSolidUser size={18} />
//                             } /> : null
//                         }


//                         <div>
//                             <button
//                                 className={`${(pathName === '/project' || pathName.includes("/project/")) || (pathName === '/project-group') ? 'bg-gradient-to-r from-[#259dab] to-[#2574ab] text-white  ' : ' text-[#505b72] hover:text-[#808084]'}  ${openPrjectAccordian && " navelement_cont "} w-full  flex duration-500 items-center justify-start px-[14px] gap-x-[12px] h-[45px] border-b border-b-solid border-b-[#eaecf0] whitespace-nowrap `}
//                                 onClick={() => setOpenProjectAccordian(prev => !prev)}>
//                                 {/* <FontAwesomeIcon className={`${(pathName === '/project' || pathName.includes("/project")) || (pathName === '/project-group' || pathName.includes("/project-group")) ? " " : " text-[#259dab]"} `} icon={faList} size="lg" /> */}
//                                 <GoProjectRoadmap  size={18} />

//                                 <div className={`w-full justify-between flex items-center`}>
//                                     <span className='uppercase text-[12px]'>Project</span>
//                                     <FontAwesomeIcon icon={faChevronDown} className={`${openPrjectAccordian && " rotate-180"} text-[12px] duration-200 ] `} />
//                                 </div>
//                             </button>

//                             <div className={`${openPrjectAccordian ? "h-[70px]" : " h-0 "} bg-[#F6F7F8] w-full duration-300 overflow-hidden pl-[1.30rem] border-b border-b-solid border-b-[#eaecf0] `}>
//                                 {decode?.claims.includes(6) ? 
//                                 <Link to={`/project`} className=''>
//                                     <div className={`${pathName === '/project' ? ' text-[#259dab] bg-[#f6f7f8] navelement-active' : ' navelement '} flex cursor-pointer h-[35px] pl-[0px] px-[0] items-center gap-x-[17px] border-b-solid border-b-[#eaecf0] whitespace-nowrap `}>


//                                         {/* <FontAwesomeIcon className={`${pathName === '/menu' || pathName.includes("/menu/") ? '' : 'text-[#259dab] ' } text-[#259dab]`} icon={faList} size="lg" /> */}

//                                         <div className={`dot1 relative`}>
//                                             <div className='dot-ani'></div>
//                                         </div>

//                                         <div className={` ${pathName === '/project' || pathName.includes("/project/") ? 'text-[#259dab] ' : 'text-[#505b72] hover:text-[#808084]'}`}>

//                                             Project</div>
//                                     </div>
//                                 </Link> : null}


//                                 {
//                                     decode?.claims.includes(1) ?
//                                      <Link to={`/project-group`}>
//                                         <div className={`${pathName === '/project-group' ? 'text-[#259dab] bg-[#f6f7f8] navelement-active ' : ' navelement '} flex cursor-pointer h-[35px] pl-[0px] px-[0] items-center gap-x-[17px]  border-b-solid border-b-[#eaecf0] whitespace-nowrap `}>
//                                             {/* <FontAwesomeIcon className={`${pathName === '/page' ? '' : 'text-[#259dab]'}`} icon={faFileLines} size="lg" /> */}
//                                             <div className={` dot1 relative `}>
//                                                 <div className='dot-ani'></div>
//                                             </div>
//                                             <div className={`${pathName === '/project-group' ? 'text-[#259dab]' : 'text-[#505b72] hover:text-[#808084]'}`}>Project Group</div>
//                                         </div>
//                                     </Link>
//                                         : null}
//                             </div>

//                         </div>






//                         {
//                             decode?.claims.includes(21) ? <NavbarLink title={"Backup Log"} link={"/backup-log"} icon={
//                                 <BsFillCloudCheckFill size={18} />
//                             } /> : null
//                         }





//                     </div>




//                 </div>
//             </div>
//         </LocalizationProvider>


//     )
// }
